### ISSUE TITLE
Dockerize this repo

### ISSUE THREAD

**Issue by davidtavarez** [davidtavarez/glucolog#57]
Implement Docker to this repo.

**Comment by sjortiz** [comment]
I would like to take this issue

**Comment by davidtavarez** [comment]
@sjortiz do it! :) please focus on have the python3 API up and running... @nromero125 please update your fork just to have the Laravel version running.

**Comment by sjortiz** [comment]
@davidtavarez I'm about to finish but I do get the following error on `RUN python migrate.py db init`

```
Traceback (most recent call last):
  File "migrate.py", line 12, in <module>
    app = create_app(CONFIG_FILE, VERSION)
  File "/app/run.py", line 14, in create_app
    app.config.from_json(config)
  File "/usr/local/lib/python3.7/site-packages/flask/config.py", line 191, in from_json
    with open(filename) as json_file:
FileNotFoundError: [Errno 2] Unable to load configuration file (No such file or directory): '/app/instance/dev.json'
```

After checking there is no dev.json inside instances, there is just testing.json

**Comment by davidtavarez** [comment]
True! feel free to add a dev.json file.

```
{
    "FLASK_ENV": "development",
    "DEBUG": true,
    "TESTING": false,
    "SECRET_KEY": "SUPERSUPERSECRETKEY0123456789!",
    "SQLALCHEMY_DATABASE_URI": "sqlite:////tmp/test.db",
    "SQLALCHEMY_TRACK_MODIFICATIONS": false
}
```
